#!/usr/bin/env bash
file_name="school"

if [ -e "$file_name" ]; then
  echo "$file_name file exists"

  if [ -s "$file_name" ]; then
    echo "$file_name is not empty"
  else
    echo "$file_name is empty"
  fi

  if [ -f "$file_name" ]; then
    echo "$file_name is a regular filw"
  fi

else
  echo "$file_name does not exist"
fi
